import React from "react";
import Head from "next/head";
import Footer from "../Footer/Footer";
import Header from "../Header/Header";
import { useEffect, useState } from "react";

export default function MainLayout({ children }) {
  const [inView, setInView] = useState(true);

  useEffect(() => {
    window.addEventListener("scroll", () => {
      const { innerHeight, pageYOffset } = window;
      setInView(innerHeight >= (pageYOffset || 0));
    });
    return window.removeEventListener("scroll", () => {
      const { innerHeight, pageYOffset } = window;
      setInView(innerHeight >= pageYOffset);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Ta Trains Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <Header inView={inView} />

      <main>{children}</main>

      <Footer />
    </>
  );
}
