import React from "react";
import Head from "next/head";
import Footer from "../Footer/Footer";
import Header from "../Header/Header";
import { useEffect, useState } from "react";

export default function MainLayout({ children }) {
  const [inView, setInView] = useState(true);
  useEffect(() => {
    window.addEventListener("scroll", () => {
      const { innerHeight, pageYOffset } = window;
      setInView(innerHeight >= (pageYOffset || 0));
    });
    return window.removeEventListener("scroll", () => {
      const { innerHeight, pageYOffset } = window;
      setInView(innerHeight >= pageYOffset);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Полиграф - Бишкек</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="Полиграф бишкек, Полиграф Бишкек, полиграф Бишкек, Полиграф тест, Калп детектору, Калп жана чындык, Чындыкты текшерүү, Басып чыгаруу, Калпты аныктоочу шайман, Вербалдык эмес сигнал детектору, Чындык машинасы, Калп жана детектор, Эмоция детектору, Полиграфиялык экспертиза, Чын же жалган текшерүү, Калпты текшерүү, Чындыкты текшерүү, Жалгандыкты текшерүү, Калп текшерүү, Полиграфолог, Адам чындыкты текшерет, Эмоцияны текшерүү, Адамды текшерүү, Актыгын текшерүү, Полиграфиялык жабдуулар, Кеп анализатору, Полиграфиялык экспертиза, Чындыкты текшерүү, Полиграфты кантип алдаса болот, Калпты аныктоочу иш жүзүндө, Полиграфия жана психология, Полиграф менен иштөө, Полиграфтын жыйынтыгы, Калпедетектор кантип иштейт, полиграф бишкек, полиграф Бишкек, полиграф Бишкек, полиграф тест, калп детектору, калп жана чындык, чындыкты текшерүү, басып чыгаруу, калпты аныктоочу шайман, вербалдык эмес сигнал детектору, чындык машинасы, калп жана детектор, эмоция детектору, полиграфиялык экспертиза, чын же жалган текшерүү, калпты текшерүү, чындыкты текшерүү, жалгандыкты текшерүү, калп текшерүү, полиграфолог, адам чындыкты текшерет, эмоцияны текшерүү, адамды текшерүү, актыгын текшерүү, полиграфиялык жабдуулар, кеп анализатору, полиграфиялык экспертиза, чындыкты текшерүү, полиграфты кантип алдаса болот, калпты аныктоочу иш жүзүндө, полиграфия жана психология, полиграф менен иштөө, полиграфтын жыйынтыгы, калпедетектор кантип иштейт, Полиграф бишкек, Детектор лжи бишкек, Полиграф Бишкек,Детектор лжи Бишкек, Полиграф тест, Детектор лжи, Ложь и правда, Тест на правду, Полиграф, Устройство для определения лжи, Детектор невербальных сигналов, Машина правды, Ложь и детектор, Детектор эмоций, Полиграфическая экспертиза, Проверка правда или ложь, Проверка на ложь, Проверка истинны, Проверка ложности, Проверка на вранье, Полиграфолог, Человек проверяет на правду, Проверка на эмоции, Проверка человека, Проверка на честность, Полиграфическое оборудование, Анализатор речи, Полиграфическая экспертиза, Тест на правду, Как обмануть полиграф, Детектор лжи на практике, Полиграфия и психология, Работа с полиграфом, Результаты полиграфа, Лжедетектор как работает, полиграф бишкек, детектор лжи бишкек, полиграф Бишкек, детектор лжи Бишкек, полиграф тест, детектор лжи, ложь и правда, тест на правду, полиграф, устройство для определения лжи, детектор невербальных сигналов, машина правды, ложь и детектор, детектор эмоций, полиграфическая экспертиза, проверка правда или ложь, проверка на ложь, проверка истинны, проверка ложности, проверка на вранье, полиграфолог, человек проверяет на правду, проверка на эмоции, проверка человека, проверка на честность, полиграфическое оборудование, анализатор речи, полиграфическая экспертиза, тест на правду, как обмануть полиграф, детектор лжи на практике, полиграфия и психология, работа с полиграфом, результаты полиграфа, лжедетектор как работает, Polygraph bishkek, Lie Detector bishkek, Polygraph Bishkek,Lie Detector Bishkek, Polygraph test, Lie detector, Lies and truth, The Truth test, Polygraph, A device for detecting lies, Non-verbal Signal Detector, Truth Machine, Lies and the detector, Emotion Detector, Polygraphic examination, Checking whether it is true or false, Checking for lies, Verification is true, Checking for falsity, Checking for lies, A polygraph examiner, A person checks for the truth, Checking for emotions, Human verification, A test of honesty, Printing equipment, Speech Analyzer, Polygraphic examination, The Truth test, How to cheat a polygraph, Lie detector in practice, Polygraphy and psychology, Working with a polygraph, Polygraph results, False detector how it works, polygraph bishkek, lie detector bishkek, polygraph Bishkek, lie detector Bishkek, polygraph test, lie detector, lie and truth, truth test, polygraph, lie detection device, non-verbal signal detector, truth machine, lie and detector, emotion detector, polygraphic examination, checking truth or lie, check for lies, check for truth, check for falsehood, check for lies, polygraph examiner, a person checks for the truth, checking for emotions, checking a person, checking for honesty, printing equipment, speech analyzer, polygraphic examination, truth test, how to cheat a polygraph, lie detector in practice, polygraphy and psychology, working with a polygraph, polygraph results,false detector how it works"
        />
        <meta
          name="google-site-verification"
          content="oSCWk-Y-_Xhyw0OYr8eI7pOkPOCGLaicG6xc04XGndc"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header inView={inView} />

      <main>{children}</main>

      <Footer />
    </>
  );
}
